##Build Stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

#Run npm to install 
RUN npm install

COPY . .

RUN npm run build

## Serve with Nginx
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]