name: Frontend CI-CD

on:
  push:
    branches:
      - main

    paths:
      - 'frontend/**'

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: frontend-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::861142265676:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
          -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
          ./frontend

      - name: Tag Docker image
        run: |
          docker tag \
          ${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Push to ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      # GitOps update
      - name: Update GitOps repo
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/jatindeshpande/gitops.git

          cd gitops/helm/devops-app/templates/frontend

          sed -i "s/tag:.*/tag: ${{ github.sha }}/" values.yaml


          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "Update frontend image tag to ${{ github.sha }}"
            git push
          fi